@startuml Use Case Diagram Hospital Management System

actor Admin
actor Doctor
actor Patient

rectangle "Hospital Management System" {

  (Manage Appointments) as UC1
  (Update Records) as UC2
  (Generate Bills) as UC3
  (View Patient Details) as UC4
  (Prescribe Medicine) as UC5
  (Register Patient) as UC6
  (Cancel Appointment) as UC7
  (Make Payment) as UC8

  UC1 .> UC6 : <<include>>
  UC1 .> UC7 : <<extend>>
  UC3 .> UC8 : <<include>>
  UC2 .> UC4 : <<include>>
}

Admin --> UC2
Admin --> UC3
Admin --> UC1

Doctor --> UC2
Doctor --> UC4
Doctor --> UC5

Patient --> UC1
Patient --> UC7
Patient --> UC8

@enduml